---
- hosts: localhost
  tasks:
    - name: Provision EC2 instance
      ec2:
         key_name: my-key1
         region: us-east-2
         instance_type: t2.micro
         image: ami-07c1207a9d40bc3bd
         wait: yes
         wait_timeout: 500
         count: 1
         instance_tags:
            Name: AWS-Ansible
         volumes:
            - device_name: /dev/xvda
              volume_type: gp2
              volume_size: 8
         monitoring: yes
         group: EC2SecurityGroup
      register: ec2

    - name: Wait for SSH to come up
      wait_for:
          host: "{{ item.public_dns_name }}"
          port: 22
          delay: 60
          timeout: 320
          state: started
      with_items: "{{ ec2.instances }}"
 
    - debug: var=ec2
    - debug: var=item
      with_items: "{{ ec2.instances }}"

    - add_host: hostname={{ item.public_ip }} groupname=ec2hosts
      with_items: "{{ ec2.instances }}"
    
    - name: Add host to group 'just_created' with variable foo=42
      add_host:
        name: '{{ ip_from_ec2 }}'
        groups: just_created
        foo: 42
    
    - ec2_eip_info:
      register: regional_eip_addresses
      