---
- hosts: localhost
  tasks:
    - name: Provision EC2 instance
      ec2:
         key_name: my-key1
         region: us-east-2
         instance_type: t2.micro
         image: ami-07c1207a9d40bc3bd
         wait: yes
         wait_timeout: 500
         count: 1
         instance_tags:
            Name: AWS-Ansible
         volumes:
            - device_name: /dev/xvda
              volume_type: gp2
              volume_size: 8
         monitoring: yes
         group: web
      register: ec2

    - name: Wait for SSH to come up
      wait_for:
          host: "{{ item.public_dns_name }}"
          port: 22
          delay: 60
          timeout: 320
          state: started
      with_items: "{{ ec2.instances }}"
      

    - name: host
        debug: msg="{{ hostvars[item]['ansible_host'] }}" 
        with_items:
          - "{{ groups['SYNC-HOSTS'] }}"

- hosts: web
  tasks:
    - name: Install Nginx Web Server
      apt:
        name=nginx
        fiestate=latest  
